MYSQL_CONFIG:
  name: 'connection-database' # 自定义次数据库链接名称
  type: mysql # 数据库链接类型
  port: '3306' # 数据库链接地址
  username: 'root' # 数据库链接用户名
  password: 'root' # 数据库链接密码
  database: 'cats_team' # 数据库名
  logging: false # 数据库打印日志
  synchronize: true # 是否开启同步数据表功能
